import distributionBrandingArtifact from '../generated/distributionBrandingArtifact.json';

type O2dCssVariableBlock = Record<string, string>;

export type O2dDistributionArtifact = {
  artifactVersion: string;
  hash: string;
  adapter: string;
  basePreset: string;
  brand: { productName: string; shortName: string };
  css: { light: O2dCssVariableBlock; dark: O2dCssVariableBlock };
};

// Pre-compiled branding artifact embedded in the build (D4, doc 05).
// Generated by packages/o2d-branding-core/scripts/generateDistributionArtifact.ts.
export const O2D_DISTRIBUTION_BRANDING =
  distributionBrandingArtifact as O2dDistributionArtifact;
