import {
  contrastRatio,
  isParsableColor,
  oklabDistance,
  parseCssColor,
  toOklch,
} from '../color/colorUtils';
import {
  normalizeBrandingConfig,
  type NormalizationResult,
} from '../normalize/normalizeBrandingConfig';
import { getPreset } from '../presets/presetRegistry';
import { brandingConfigSchema } from '../schemas/brandingConfigSchema';
import {
  REQUIRED_TOKEN_PATHS,
  TOKEN_CATALOG,
} from '../tokens/tokenCatalog';
import {
  type O2DBrandingConfig,
  type TokenMode,
  type ValidationIssue,
  type ValidationResult,
} from '../types/branding.types';

const MODES: TokenMode[] = ['light', 'dark'];

// Anti-injection guard for values that end up inside a CSS declaration
// (doc 17): only typed literals, no structural characters or references.
const CSS_INJECTION_PATTERN = /[;{}<>]|url\s*\(|expression|@import/i;
const EXTERNAL_URL_PATTERN = /https?:|\/\//;

const A1_PAIRS: Array<[foreground: string, background: string]> = [
  ['text.primary', 'background.primary'],
  ['text.primary', 'background.secondary'],
  ['text.primary', 'background.tertiary'],
  ['text.primary', 'surface.primary'],
  ['text.primary', 'surface.secondary'],
  ['text.secondary', 'background.primary'],
  ['text.secondary', 'surface.primary'],
];

const STATUS_TOKEN_PATHS = [
  'status.success',
  'status.warning',
  'status.error',
  'status.info',
];

const MINIMUM_HOVER_DELTA_LIGHTNESS = 0.015;
const MINIMUM_STATUS_DISTANCE = 0.05;

const toPx = (value: string): number | null => {
  const match = value.trim().match(/^(-?[\d.]+)(px|rem|em)?$/);

  if (match === null) {
    return null;
  }

  const numeric = Number(match[1]);

  return match[2] === 'rem' || match[2] === 'em' ? numeric * 16 : numeric;
};

// Full validation pipeline (doc 06 §4): structure → tiers → values →
// required tokens → accessibility invariants A1–A7 (doc 16), both modes.
export const validateBrandingConfig = (
  config: O2DBrandingConfig,
): ValidationResult & { normalization: NormalizationResult | null } => {
  const issues: ValidationIssue[] = [];

  const parsedSchema = brandingConfigSchema.safeParse(config);

  if (!parsedSchema.success) {
    for (const schemaIssue of parsedSchema.error.issues) {
      issues.push({
        rule: 'schema',
        severity: 'error',
        message: `${schemaIssue.path.join('.') || '(root)'}: ${schemaIssue.message}`,
      });
    }

    return { status: 'failed', issues, normalization: null };
  }

  for (const path of Object.keys(config.tokens)) {
    const tier = TOKEN_CATALOG[path]?.tier;

    if (tier === 'calculated') {
      issues.push({
        rule: 'tier.calculated',
        severity: 'error',
        tokenPath: path,
        message: `${path} is a calculated token — always generated by the core, never set directly`,
      });
    }

    if (tier === 'readonly') {
      issues.push({
        rule: 'tier.readonly',
        severity: 'error',
        tokenPath: path,
        message: `${path} is read-only in this version (doc 09 §2.3)`,
      });
    }
  }

  const normalization = normalizeBrandingConfig(config);

  issues.push(...normalization.issues);

  const { resolved, overriddenPaths, derivedPaths } = normalization;

  if (resolved === null) {
    return { status: 'failed', issues, normalization };
  }

  const preset = getPreset(config.basePreset);

  // A customization is judged strictly; values inherited untouched from the
  // baseline preset are reported as warnings instead of blocking, because
  // the upstream baseline is the accessibility reference (doc 16 §1). Values
  // the core derived itself carry the same upstream visual profile (the
  // reference curve), so they get the same treatment — only explicit client
  // overrides block.
  const isBaselineValue = (path: string, mode: TokenMode): boolean => {
    if (derivedPaths.has(path) && !overriddenPaths.has(path)) {
      return true;
    }

    const presetValue = preset?.tokens[path]?.[mode];

    return (
      presetValue !== undefined && resolved.tokens[mode][path] === presetValue
    );
  };

  for (const mode of MODES) {
    for (const [path, value] of Object.entries(resolved.tokens[mode])) {
      const entry = TOKEN_CATALOG[path];

      if (entry === undefined) {
        continue;
      }

      if (typeof value === 'string' && CSS_INJECTION_PATTERN.test(value)) {
        issues.push({
          rule: 'css.injection',
          severity: 'error',
          tokenPath: path,
          mode,
          message: `${path} contains characters that are not allowed in token values`,
        });
        continue;
      }

      if (
        typeof value === 'string' &&
        entry.type !== 'fontFamily' &&
        EXTERNAL_URL_PATTERN.test(value)
      ) {
        issues.push({
          rule: 'url.external',
          severity: 'error',
          tokenPath: path,
          mode,
          message: `${path} must not reference URLs — assets travel by assetId only`,
        });
        continue;
      }

      if (entry.type === 'color' && typeof value === 'string') {
        if (!isParsableColor(value)) {
          issues.push({
            rule: 'color.format',
            severity: 'error',
            tokenPath: path,
            mode,
            message: `${path} value "${value}" is not a valid color (hex, rgb() or color(display-p3))`,
          });
        }
      }

      if (entry.type === 'dimension' && overriddenPaths.has(path)) {
        const px = toPx(String(value));

        if (px === null) {
          issues.push({
            rule: 'dimension.invalid',
            severity: 'error',
            tokenPath: path,
            mode,
            message: `${path} value "${value}" is not a px/rem/em dimension`,
          });
        } else {
          const min = entry.min !== undefined ? toPx(entry.min) : null;
          const max = entry.max !== undefined ? toPx(entry.max) : null;

          if ((min !== null && px < min) || (max !== null && px > max)) {
            issues.push({
              rule: 'dimension.bounds',
              severity: 'error',
              tokenPath: path,
              mode,
              measured: String(value),
              required: `[${entry.min ?? '-∞'}, ${entry.max ?? '∞'}]`,
              message: `${path} is outside the allowed range — values are rejected, never clamped (doc 06 §4)`,
            });
          }
        }
      }
    }

    for (const path of REQUIRED_TOKEN_PATHS) {
      if (resolved.tokens[mode][path] === undefined) {
        issues.push({
          rule: 'required.missing',
          severity: 'error',
          tokenPath: path,
          mode,
          message: `required token ${path} is absent after normalization`,
        });
      }
    }

    const colorAt = (path: string) => {
      const value = resolved.tokens[mode][path];

      return typeof value === 'string' ? parseCssColor(value) : null;
    };

    const contrastRule = (
      rule: string,
      foregroundPath: string,
      backgroundPath: string,
      minimum: number,
      aaaThreshold?: number,
    ): void => {
      const foreground = colorAt(foregroundPath);
      const background = colorAt(backgroundPath);

      if (foreground === null || background === null) {
        return;
      }

      const measured = contrastRatio(foreground, background);

      if (measured < minimum) {
        const baseline =
          isBaselineValue(foregroundPath, mode) &&
          isBaselineValue(backgroundPath, mode);

        issues.push({
          rule: baseline ? `${rule}.baseline` : rule,
          severity: baseline ? 'warning' : 'error',
          tokenPath: foregroundPath,
          mode,
          measured: measured.toFixed(2),
          required: minimum.toFixed(2),
          message: `${foregroundPath} on ${backgroundPath} measures ${measured.toFixed(2)}:1, minimum is ${minimum}:1${baseline ? ' (inherited from upstream baseline — not blocking)' : ''}`,
        });
      } else if (aaaThreshold !== undefined && measured < aaaThreshold) {
        issues.push({
          rule: 'contrast.aaa',
          severity: 'warning',
          tokenPath: foregroundPath,
          mode,
          measured: measured.toFixed(2),
          required: aaaThreshold.toFixed(2),
          message: `${foregroundPath} on ${backgroundPath} passes AA but not AAA (${measured.toFixed(2)}:1)`,
        });
      }
    };

    // A1 — normal text ≥ 4.5:1 (warning band up to 7:1 for AAA).
    for (const [foregroundPath, backgroundPath] of A1_PAIRS) {
      contrastRule('contrast.a1', foregroundPath, backgroundPath, 4.5, 7);
    }

    // A2 — text/UI on the solid brand color ≥ 3:1.
    contrastRule('contrast.a2', 'brand.onPrimary', 'brand.primary', 3);

    // A3 — focus ring ≥ 3:1 against the adjacent background.
    contrastRule('contrast.a3', 'border.focus', 'background.primary', 3);

    // A5 — hover state must remain perceptibly distinct.
    const brandPrimary = colorAt('brand.primary');
    const brandPrimaryHover = colorAt('brand.primaryHover');

    if (brandPrimary !== null && brandPrimaryHover !== null) {
      const delta = Math.abs(
        toOklch(brandPrimary).l - toOklch(brandPrimaryHover).l,
      );

      if (delta < MINIMUM_HOVER_DELTA_LIGHTNESS) {
        const baseline =
          isBaselineValue('brand.primary', mode) &&
          isBaselineValue('brand.primaryHover', mode);

        issues.push({
          rule: baseline ? 'derived.a5.baseline' : 'derived.a5',
          severity: baseline ? 'warning' : 'error',
          tokenPath: 'brand.primaryHover',
          mode,
          measured: delta.toFixed(4),
          required: MINIMUM_HOVER_DELTA_LIGHTNESS.toFixed(4),
          message: 'hover state is not perceptibly distinct from the base state (A5)',
        });
      }
    }

    // A7 — status colors must stay pairwise distinguishable.
    for (let indexA = 0; indexA < STATUS_TOKEN_PATHS.length; indexA += 1) {
      for (
        let indexB = indexA + 1;
        indexB < STATUS_TOKEN_PATHS.length;
        indexB += 1
      ) {
        const colorA = colorAt(STATUS_TOKEN_PATHS[indexA]);
        const colorB = colorAt(STATUS_TOKEN_PATHS[indexB]);

        if (colorA === null || colorB === null) {
          continue;
        }

        const distance = oklabDistance(colorA, colorB);

        if (distance < MINIMUM_STATUS_DISTANCE) {
          const baseline =
            isBaselineValue(STATUS_TOKEN_PATHS[indexA], mode) &&
            isBaselineValue(STATUS_TOKEN_PATHS[indexB], mode);

          issues.push({
            rule: baseline ? 'status.a7.baseline' : 'status.a7',
            severity: baseline ? 'warning' : 'error',
            tokenPath: STATUS_TOKEN_PATHS[indexB],
            mode,
            measured: distance.toFixed(4),
            required: MINIMUM_STATUS_DISTANCE.toFixed(4),
            message: `${STATUS_TOKEN_PATHS[indexA]} and ${STATUS_TOKEN_PATHS[indexB]} are not distinguishable (A7)`,
          });
        }
      }
    }
  }

  const hasError = issues.some((issue) => issue.severity === 'error');

  return {
    status: hasError ? 'failed' : 'valid',
    issues,
    normalization,
  };
};
